copy test results catkin

diff --git a/catkin_make_repo b/catkin_make_repo
--- a/catkin_make_repo
+++ b/catkin_make_repo
@@ -11,8 +11,14 @@ if [ $# -eq 0 ]
     catkin_make run_tests
 fi
 
+# Die if make test fails.
+ret_code=$?
+if [ $ret_code != 0 ]; then
+  exit $ret_code
+fi
+
 # Clear out results from the requested packages.
-TEST_RESULTS_FOLDER=$WORKSPACE/build/test_results/
+TEST_RESULTS_FOLDER=$WORKSPACE/build/test_results
 for package in $@
 do
     echo "Clearing test results in $TEST_RESULTS_FOLDER/$package ..."
