only copy test results when testing

diff --git a/catkin_make_repo b/catkin_make_repo
--- a/catkin_make_repo
+++ b/catkin_make_repo
@@ -28,27 +28,27 @@ if [ "$PACKAGES" = "" ]  || [ "$PACKAGES" = " " ]; then
 fi
 if $RUN_TESTS; then
   catkin_make run_tests
+  # Die if make test fails.
+  ret_code=$?
+  if [ $ret_code != 0 ]; then
+    exit $ret_code
+  fi
+
+  # Clear out results from the requested packages.
+  TEST_RESULTS_FOLDER=$WORKSPACE/build/test_results
+  for package in $@
+  do
+      echo "Clearing test results in $TEST_RESULTS_FOLDER/$package ..."
+      rm -rf $TEST_RESULTS_FOLDER/$package
+  done
+
+  # Clear / Create a directory in the workspace where we can store the test results.
+  TEST_RESULTS_DEST=$WORKSPACE/test_results/
+  rm -rf $TEST_RESULTS_DEST
+  mkdir -p $TEST_RESULTS_DEST
+
+  # Copy all test results from the currently build packages to the workspace folder.
+  echo "Copying test results from $TEST_RESULTS_FOLDER/$package to $TEST_RESULTS_DEST..."
+  cp -r $TEST_RESULTS_FOLDER/* $TEST_RESULTS_DEST/ || true
 fi
 
-# Die if make test fails.
-ret_code=$?
-if [ $ret_code != 0 ]; then
-  exit $ret_code
-fi
-
-# Clear out results from the requested packages.
-TEST_RESULTS_FOLDER=$WORKSPACE/build/test_results
-for package in $@
-do
-    echo "Clearing test results in $TEST_RESULTS_FOLDER/$package ..."
-    rm -rf $TEST_RESULTS_FOLDER/$package
-done
-
-# Clear / Create a directory in the workspace where we can store the test results.
-TEST_RESULTS_DEST=$WORKSPACE/test_results/
-rm -rf $TEST_RESULTS_DEST
-mkdir -p $TEST_RESULTS_DEST
-
-# Copy all test results from the currently build packages to the workspace folder.
-echo "Copying test results from $TEST_RESULTS_FOLDER/$package to $TEST_RESULTS_DEST..."
-cp -r $TEST_RESULTS_FOLDER/* $TEST_RESULTS_DEST/ || true
