Update catkin_make_repo

diff --git a/catkin_make_repo b/catkin_make_repo
--- a/catkin_make_repo
+++ b/catkin_make_repo
@@ -41,16 +41,13 @@ if $RUN_TESTS; then
       rm -rf $TEST_RESULTS_FOLDER/$package
   done
 
-  for PACKAGE in $PACKAGES
-  do
-    catkin_make run_tests_$PACKAGE
-    # Die if make test fails.
-    ret_code=$?
-    if [ $ret_code != 0 ]; then
-      exit $ret_code
-    fi
-  done
-
+  catkin_make run_tests
+  # Die if make test fails.
+  ret_code=$?
+  if [ $ret_code != 0 ]; then
+    exit $ret_code
+  fi
+  
   # Clear / Create a directory in the workspace where we can store the test results.
   TEST_RESULTS_DEST=$WORKSPACE/test_results/
   rm -rf $TEST_RESULTS_DEST
