Die if make test fails

diff --git a/rosmake_repo b/rosmake_repo
--- a/rosmake_repo
+++ b/rosmake_repo
@@ -32,6 +32,12 @@ done
 # Run the tests.
 VERBOSE=1 rosmake $@ -V --test-only
 
+# Die if make test fails.
+ret_code=$?
+if [ $ret_code != 0 ]; then
+  exit $ret_code
+fi
+
 # Clear / Create a directory in the workspace where we can store the test results.
 TEST_RESULTS_DEST=$WORKSPACE/test_results/
 rm -rf $TEST_RESULTS_DEST
